[33mcommit 33d38f45fe3324d5724bca78bb6d0797ee452582[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m)[m
Author: ssemujjukennedy84-hash <ssemujjukennedy84@gmail.com>
Date:   Mon Jun 22 09:46:11 2026 +0300

    Shadow - Unified Strategic Intelligence Platform

.env
api/__pycache__/server.cpython-314.pyc
api/server.py
backtest.py
backtest_trading.py
backtest_trading_full.py
backtest_trading_shadow.py
check_backtest.py
check_balance.py
check_results.py
check_status.py
dashboard-html/index.html
dashboard/app.py
data/__pycache__/complete_engine.cpython-314.pyc
data/__pycache__/engine.cpython-314.pyc
data/art_of_war.txt
data/chapters/chapter_01_laying_plans.txt
data/chapters/chapter_02_waging_war.txt
data/chapters/chapter_03_attack_by_stratagem.txt
data/chapters/chapter_04_tactical_dispositions.txt
data/chapters/chapter_05_energy.txt
data/chapters/chapter_06_weak_points_and_strong.txt
data/chapters/chapter_07_maneuvering.txt
data/chapters/chapter_08_variation_in_tactics.txt
data/chapters/chapter_09_the_army_on_the_march.txt
data/chapters/chapter_10_terrain.txt
data/chapters/chapter_11_the_nine_situations.txt
data/chapters/chapter_12_attack_by_fire.txt
data/chapters/chapter_13_use_of_spies.txt
data/chroma_db/3664f28e-718a-42c9-99aa-a86dac43c72c/data_level0.bin
data/chroma_db/3664f28e-718a-42c9-99aa-a86dac43c72c/header.bin
data/chroma_db/3664f28e-718a-42c9-99aa-a86dac43c72c/length.bin
data/chroma_db/3664f28e-718a-42c9-99aa-a86dac43c72c/link_lists.bin
data/chroma_db/chroma.sqlite3
data/complete_engine.py
data/offline_matches/bundesliga.json
data/offline_matches/epl.json
data/offline_matches/laliga.json
data/offline_matches/ligue1.json
data/offline_matches/seriea.json
data/shadow_history.db
db_check.py
download_all_leagues.py
engine/__pycache__/art_of_war_rag.cpython-314.pyc
engine/__pycache__/combined_trading.cpython-314.pyc
engine/__pycache__/data_mapper.cpython-314.pyc
engine/__pycache__/quant_engine.cpython-314.pyc
engine/__pycache__/sun_tzu_engine.cpython-314.pyc
engine/__pycache__/sun_tzu_mind.cpython-314.pyc
engine/__pycache__/sun_tzu_trading.cpython-314.pyc
engine/__pycache__/thirteen_audit.cpython-314.pyc
engine/__pycache__/trading_engine.cpython-314.pyc
engine/art_of_war_rag.py
engine/chapters/__pycache__/chapter_01.cpython-314.pyc
engine/chapters/__pycache__/chapter_02.cpython-314.pyc
engine/chapters/__pycache__/chapter_03.cpython-314.pyc
engine/chapters/__pycache__/chapter_04.cpython-314.pyc
engine/chapters/__pycache__/chapter_05.cpython-314.pyc
engine/chapters/__pycache__/chapter_06.cpython-314.pyc
engine/chapters/__pycache__/chapter_07.cpython-314.pyc
engine/chapters/__pycache__/chapter_08.cpython-314.pyc
engine/chapters/__pycache__/chapter_09.cpython-314.pyc
engine/chapters/__pycache__/chapter_10.cpython-314.pyc
engine/chapters/__pycache__/chapter_11.cpython-314.pyc
engine/chapters/__pycache__/chapter_12.cpython-314.pyc
engine/chapters/__pycache__/chapter_13.cpython-314.pyc
engine/chapters/chapter_01.py
engine/chapters/chapter_02.py
engine/chapters/chapter_03.py
engine/chapters/chapter_04.py
engine/chapters/chapter_05.py
engine/chapters/chapter_06.py
engine/chapters/chapter_07.py
engine/chapters/chapter_08.py
engine/chapters/chapter_09.py
engine/chapters/chapter_10.py
engine/chapters/chapter_11.py
engine/chapters/chapter_12.py
engine/chapters/chapter_13.py
engine/chapters_trading/__pycache__/chapter_01.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_02.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_03.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_04.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_05.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_06.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_08.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_09.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_10.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_11.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_12.cpython-314.pyc
engine/chapters_trading/__pycache__/chapter_13.cpython-314.pyc
engine/chapters_trading/chapter_01.py
engine/chapters_trading/chapter_02.py
engine/chapters_trading/chapter_03.py
engine/chapters_trading/chapter_04.py
engine/chapters_trading/chapter_05.py
engine/chapters_trading/chapter_06.py
engine/chapters_trading/chapter_07.py
engine/chapters_trading/chapter_08.py
engine/chapters_trading/chapter_09.py
engine/chapters_trading/chapter_10.py
engine/chapters_trading/chapter_11.py
engine/chapters_trading/chapter_12.py
engine/chapters_trading/chapter_13.py
engine/combined_trading.py
engine/data_mapper.py
engine/quant_engine.py
engine/sun_tzu_engine.py
engine/sun_tzu_mind.py
engine/sun_tzu_trading.py
engine/sun_tzu_vectorized.py
engine/thirteen_audit.py
engine/trading_engine.py
engine/wyckoff/__pycache__/engine.cpython-314.pyc
engine/wyckoff/engine.py
ontology/army.py
ontology/battlefield.py
shadow_web.py
split_chapters.py
test_api.py
test_api2.py
test_api_football.py
test_apis.py
test_audit.py
test_backtest_logic.py
test_fifa.py
test_fifa2.py
test_fifa3.py
test_mapped.py
test_official.py
test_ollama.py
test_ollama_audit.py
test_sun_tzu.py
test_wc.py
test_wc_id.py
test_wc_live.py
