"""Shadow - Chapter 1: Laying Plans"""

def CHAPTER_1_RULES():
    return [
        ("1. Art of war is of vital importance to the State", lambda e: "PRO" if e.get("importance",5) > 5 else "NEUTRAL"),
        ("2. It is a matter of life and death", lambda e: "PRO" if e.get("must_win",False) else "NEUTRAL"),
        ("3. A road either to safety or to ruin", lambda e: "CON" if e.get("risk_level",0) > 7 else "NEUTRAL"),
        ("4. It is a subject of inquiry which can on no account be neglected", lambda e: "PRO" if e.get("preparation",5) > 5 else "CON" if e.get("preparation",5) < 3 else "NEUTRAL"),
        ("5. The art of war is governed by five constant factors", lambda e1,e2: "PRO" if e1.get("five_score",5) > e2.get("five_score",5)+2 else "CON" if e2.get("five_score",5) > e1.get("five_score",5)+2 else "NEUTRAL"),
        ("6. These must be taken into account in one's deliberations", lambda e: "PRO" if e.get("intelligence",5) > 5 else "NEUTRAL"),
        ("7. When seeking to determine the conditions obtaining in the field", lambda e: "PRO" if e.get("preparation",5) > 5 else "NEUTRAL"),
        ("8. The Moral Law causes the people to be in complete accord with their ruler", lambda e1,e2: "PRO" if e1.get("team_harmony",5) > e2.get("team_harmony",5)+2 else "CON" if e2.get("team_harmony",5) > e1.get("team_harmony",5)+2 else "NEUTRAL"),
        ("9. So that they will follow him regardless of their lives", lambda e: "PRO" if e.get("morale",5) > 8 else "CON" if e.get("morale",5) < 4 else "NEUTRAL"),
        ("10. Undismayed by any danger", lambda e: "PRO" if e.get("comeback_wins",0) > 2 else "NEUTRAL"),
        ("11. The Moral Law: unity of purpose between ruler and people", lambda e: "PRO" if e.get("team_harmony",5) > 7 else "CON" if e.get("team_harmony",5) < 4 else "NEUTRAL"),
        ("12. Heaven signifies night and day", lambda e1,e2: "PRO" if e1.get("rest_days",7) > e2.get("rest_days",7)+1 else "CON" if e2.get("rest_days",7) > e1.get("rest_days",7)+1 else "NEUTRAL"),
        ("13. Heaven signifies cold and heat", lambda e1,e2: "PRO" if e1.get("weather","") in ["Clear","Cloudy","Warm","Hot"] and e2.get("weather","") in ["Rain","Storm","Snow","Cold"] else "CON" if e2.get("weather","") in ["Clear","Cloudy","Warm","Hot"] and e1.get("weather","") in ["Rain","Storm","Snow","Cold"] else "NEUTRAL"),
        ("14. Heaven signifies times and seasons", lambda e: "PRO" if e.get("season_advantage",False) else "NEUTRAL"),
        ("15. Heaven includes favorable timing for engagement", lambda e: "PRO" if e.get("time_advantage",False) else "NEUTRAL"),
        ("16. Heaven determines when to fight and when to wait", lambda e: "PRO" if e.get("rest_days",7) > 5 else "NEUTRAL"),
        ("17. Earth comprises distances, great and small", lambda e1,e2: "PRO" if e1.get("travel_distance",0) < e2.get("travel_distance",0) else "CON" if e2.get("travel_distance",0) < e1.get("travel_distance",0) else "NEUTRAL"),
        ("18. Earth comprises danger and security", lambda e1,e2: "PRO" if e1.get("home_away","") == "home" else "CON" if e2.get("home_away","") == "home" else "NEUTRAL"),
        ("19. Earth comprises open ground and narrow passes", lambda e1,e2: "PRO" if e1.get("capacity",0) > e2.get("capacity",0)*1.5 else "CON" if e2.get("capacity",0) > e1.get("capacity",0)*1.5 else "NEUTRAL"),
        ("20. Earth comprises the chances of life and death", lambda e1,e2: "PRO" if e1.get("strength",5) > e2.get("strength",5)*1.3 else "CON" if e2.get("strength",5) > e1.get("strength",5)*1.3 else "NEUTRAL"),
        ("21. Earth: the terrain determines the battle", lambda e: "PRO" if e.get("pitch_condition","good") == "good" and e.get("home_away","") == "home" else "NEUTRAL"),
        ("22. Earth includes altitude advantage", lambda e1,e2: "PRO" if e1.get("altitude",0) > e2.get("altitude",0)+500 else "NEUTRAL"),
        ("23. The Commander stands for the virtue of wisdom", lambda e1,e2: "PRO" if e1.get("manager_quality",5) > e2.get("manager_quality",5)+1 else "CON" if e2.get("manager_quality",5) > e1.get("manager_quality",5)+1 else "NEUTRAL"),
        ("24. The Commander stands for sincerity", lambda e1,e2: "PRO" if e1.get("discipline",5) > e2.get("discipline",5)+1 else "CON" if e2.get("discipline",5) > e1.get("discipline",5)+1 else "NEUTRAL"),
        ("25. The Commander stands for benevolence", lambda e1,e2: "PRO" if e1.get("team_harmony",5) > e2.get("team_harmony",5)+1 else "CON" if e2.get("team_harmony",5) > e1.get("team_harmony",5)+1 else "NEUTRAL"),
        ("26. The Commander stands for courage", lambda e1,e2: "PRO" if e1.get("comeback_wins",0) > e2.get("comeback_wins",0) else "NEUTRAL"),
        ("27. The Commander stands for strictness", lambda e: "PRO" if e.get("discipline",5) > 7 else "CON" if e.get("discipline",5) < 4 else "NEUTRAL"),
        ("28. A commander must possess all five virtues", lambda e: "PRO" if e.get("manager_quality",5)>6 and e.get("discipline",5)>6 and e.get("team_harmony",5)>6 else "NEUTRAL"),
        ("29. Without all five, the army is incomplete", lambda e: "CON" if e.get("manager_quality",5)<5 or e.get("discipline",5)<5 or e.get("team_harmony",5)<5 else "NEUTRAL"),
        ("30. Method: the marshaling of the army in its proper subdivisions", lambda e1,e2: "PRO" if e1.get("squad_depth",0) > e2.get("squad_depth",0)*1.2 else "CON" if e2.get("squad_depth",0) > e1.get("squad_depth",0)*1.2 else "NEUTRAL"),
        ("31. Method: the graduations of rank among the officers", lambda e: "PRO" if e.get("organization",5) > 5 else "NEUTRAL"),
        ("32. Method: the maintenance of roads by which supplies may reach the army", lambda e: "PRO" if e.get("supply_line",5) > 5 else "NEUTRAL"),
        ("33. Method: the control of military expenditure", lambda e1,e2: "PRO" if e1.get("squad_value",0) > e2.get("squad_value",0)*1.3 else "CON" if e2.get("squad_value",0) > e1.get("squad_value",0)*1.3 else "NEUTRAL"),
        ("34. Method: efficiency in logistics wins wars", lambda e: "PRO" if e.get("supply_line",5) > 6 and e.get("organization",5) > 6 else "NEUTRAL"),
        ("35. These five heads should be familiar to every general", lambda e: "PRO" if e.get("five_score",5) > 5 else "NEUTRAL"),
        ("36. He who knows them will be victorious", lambda e1,e2: "PRO" if e1.get("intelligence",5) > e2.get("intelligence",5)+1 else "CON" if e2.get("intelligence",5) > e1.get("intelligence",5)+1 else "NEUTRAL"),
        ("37. He who knows them not will fail", lambda e: "CON" if e.get("intelligence",5) < 4 else "NEUTRAL"),
        ("38. Let the five heads be made the basis of a comparison", lambda e: "PRO" if e.get("intelligence",5) > 5 else "NEUTRAL"),
        ("39. C1: Which of the two sovereigns is imbued with the Moral Law?", lambda e1,e2: "PRO" if e1.get("team_harmony",5) > e2.get("team_harmony",5)+1 else "CON" if e2.get("team_harmony",5) > e1.get("team_harmony",5)+1 else "NEUTRAL"),
        ("40. C2: Which of the two generals has most ability?", lambda e1,e2: "PRO" if e1.get("manager_quality",5) > e2.get("manager_quality",5)+1 else "CON" if e2.get("manager_quality",5) > e1.get("manager_quality",5)+1 else "NEUTRAL"),
        ("41. C3: With whom lie the advantages derived from Heaven and Earth?", lambda e1,e2: "PRO" if e1.get("home_away","")=="home" and e1.get("weather","") in ["Clear","Cloudy"] else "CON" if e2.get("home_away","")=="home" and e2.get("weather","") in ["Clear","Cloudy"] else "NEUTRAL"),
        ("42. C4: On which side is discipline most rigorously enforced?", lambda e1,e2: "PRO" if e1.get("discipline",5) > e2.get("discipline",5)+1 else "CON" if e2.get("discipline",5) > e1.get("discipline",5)+1 else "NEUTRAL"),
        ("43. C5: Which army is stronger?", lambda e1,e2: "PRO" if e1.get("strength",5) > e2.get("strength",5)*1.2 else "CON" if e2.get("strength",5) > e1.get("strength",5)*1.2 else "NEUTRAL"),
        ("44. C6: On which side are officers and men more highly trained?", lambda e1,e2: "PRO" if e1.get("played",0) > e2.get("played",0)+5 else "CON" if e2.get("played",0) > e1.get("played",0)+5 else "NEUTRAL"),
        ("45. C7: In which army is there greater constancy in reward and punishment?", lambda e1,e2: "PRO" if e1.get("form","").count("W") > e2.get("form","").count("W")+2 else "CON" if e2.get("form","").count("W") > e1.get("form","").count("W")+2 else "NEUTRAL"),
        ("46. By means of these seven considerations I can forecast victory or defeat", lambda e1,e2: "PRO" if e1.get("seven_score",5) > e2.get("seven_score",5)+2 else "NEUTRAL"),
        ("47. The general who hearkens to my counsel and acts upon it will conquer", lambda e1,e2: "PRO" if e1.get("intelligence",5) > e2.get("intelligence",5) else "NEUTRAL"),
        ("48. Let such a one be retained in command", lambda e: "PRO" if e.get("manager_quality",5) > 7 else "NEUTRAL"),
        ("49. The general who hearkens not will suffer defeat", lambda e: "CON" if e.get("intelligence",5) < 4 else "NEUTRAL"),
        ("50. Let such a one be dismissed", lambda e: "CON" if e.get("manager_quality",5) < 4 else "NEUTRAL"),
        ("51. While heeding the profit of my counsel, avail yourself of any helpful circumstances", lambda e: "PRO" if e.get("counter_attack",0) > 0 or e.get("set_pieces",0) > 0 else "NEUTRAL"),
        ("52. According as circumstances are favorable, one should modify one's plans", lambda e: "PRO" if e.get("formation_changes",0) > 2 else "NEUTRAL"),
        ("53. All warfare is based on deception", lambda e1,e2: "PRO" if e1.get("counter_attack",0) > e2.get("counter_attack",0)+2 else "CON" if e2.get("counter_attack",0) > e1.get("counter_attack",0)+2 else "NEUTRAL"),
        ("54. When able to attack, we must seem unable", lambda e1,e2: "PRO" if e1.get("strength",5) > e2.get("strength",5) and e1.get("form","").count("L") >= 1 else "NEUTRAL"),
        ("55. When using our forces, we must seem inactive", lambda e1,e2: "PRO" if e1.get("energy",50) < 60 and e1.get("strength",5) > e2.get("strength",5) else "NEUTRAL"),
        ("56. When we are near, make the enemy believe we are far away", lambda e: "PRO" if e.get("counter_attack",0) > 2 else "NEUTRAL"),
        ("57. When far away, make him believe we are near", lambda e: "PRO" if e.get("travel_distance",0) > 3000 and e.get("energy",50) > 60 else "NEUTRAL"),
        ("58. Hold out baits to entice the enemy", lambda e1,e2: "PRO" if e1.get("counter_attack",0) > e2.get("counter_attack",0) else "NEUTRAL"),
        ("59. Feign disorder, and crush him", lambda e: "PRO" if e.get("comeback_wins",0) > 1 else "NEUTRAL"),
        ("60. If he is secure at all points, be prepared for him", lambda e1,e2: "PRO" if e2.get("clean_sheets",0) > 3 and e1.get("preparation",5) > 6 else "NEUTRAL"),
        ("61. If he is in superior strength, evade him", lambda e1,e2: "CON" if e2.get("strength",5) > e1.get("strength",5)*1.3 else "NEUTRAL"),
        ("62. If your opponent is of choleric temper, seek to irritate him", lambda e1,e2: "PRO" if e2.get("discipline",5) < 4 else "NEUTRAL"),
        ("63. Pretend to be weak, that he may grow arrogant", lambda e1,e2: "PRO" if e1.get("strength",5) < 5 and e2.get("strength",5) > 7 else "NEUTRAL"),
        ("64. If he is taking his ease, give him no rest", lambda e1,e2: "PRO" if e2.get("rest_days",7) > 7 and e1.get("energy",50) > 70 else "NEUTRAL"),
        ("65. If his forces are united, separate them", lambda e1,e2: "PRO" if e1.get("counter_attack",0) > 0 and e2.get("team_harmony",5) > 7 else "NEUTRAL"),
        ("66. Attack him where he is unprepared", lambda e1,e2: "PRO" if e2.get("injury_count",0) > e1.get("injury_count",0)+2 else "CON" if e1.get("injury_count",0) > e2.get("injury_count",0)+2 else "NEUTRAL"),
        ("67. Appear where you are not expected", lambda e1,e2: "PRO" if e1.get("away_wins",0) > e2.get("away_wins",0) else "NEUTRAL"),
        ("68. These military devices, leading to victory, must not be divulged beforehand", lambda e: "PRO" if e.get("intelligence",5) > 5 else "NEUTRAL"),
        ("69. The general who wins a battle makes many calculations in his temple before the battle is fought", lambda e1,e2: "PRO" if e1.get("intelligence",5) > e2.get("intelligence",5)+1 and e1.get("preparation",5) > e2.get("preparation",5) else "CON" if e2.get("intelligence",5) > e1.get("intelligence",5)+1 else "NEUTRAL"),
        ("70. The general who loses a battle makes but few calculations beforehand", lambda e: "CON" if e.get("preparation",5) < 4 else "NEUTRAL"),
        ("71. Thus do many calculations lead to victory", lambda e1,e2: "PRO" if e1.get("intelligence",5) > e2.get("intelligence",5)+1 else "CON" if e2.get("intelligence",5) > e1.get("intelligence",5)+1 else "NEUTRAL"),
        ("72. Few calculations lead to defeat", lambda e: "CON" if e.get("intelligence",5) < 4 else "NEUTRAL"),
        ("73. How much more no calculation at all!", lambda e: "CON" if e.get("intelligence",5) < 3 else "NEUTRAL"),
        ("74. It is by attention to this point that I can foresee who is likely to win or lose", lambda e1,e2: "PRO" if e1.get("intelligence",5) > e2.get("intelligence",5) and e1.get("preparation",5) > e2.get("preparation",5) else "NEUTRAL"),
    ]


if __name__ == "__main__":
    rules = CHAPTER_1_RULES()
    print(f"Chapter 1: {len(rules)} principles loaded")